recipes.main.index:
  path: /
  defaults: { _controller: FtdysaRecipeBundle:Main:index }

recipes.main.search:
  path: /search
  defaults: { _controller: FtdysaRecipeBundle:Main:search }

recipes.main.add:
  path: /recipes/add
  defaults: { _controller: FtdysaRecipeBundle:Recipe:add }