recipes.main.index:
  path: /
  defaults: { _controller: FtdysaRecipeBundle:Main:index }

recipes.main.search:
  path: /search
  defaults: { _controller: FtdysaRecipeBundle:Main:search }

recipes.recipe.add:
  path: /recipes/add
  defaults: { _controller: FtdysaRecipeBundle:Recipe:add }

recipes.recipe.view:
  path: /recipe/view/{id}
  defaults: { _controller: FtdysaRecipeBundle:Recipe:view }